export type Product = {
  id: number;
  slug: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  oldPrice?: number;
  badge?: string;
  rating: number;
  reviews: number;
  image: string;
  blurb: string;
  stock: number;
  warranty: string;
  condition: "New" | "UK Used";
  highlights: string[];
  specs: Record<string, string>;
};

export const products: Product[] = [
  {
    id: 1,
    slug: "iphone-16-pro-max-256gb",
    name: "iPhone 16 Pro Max 256GB",
    brand: "Apple",
    category: "Phones",
    price: 2299000,
    oldPrice: 2499000,
    badge: "Bestseller",
    rating: 0,
    reviews: 0,
    stock: 8,
    condition: "New",
    warranty: "1 year seller warranty",
    image: "/products/iphone-16-pro-max-256gb.webp",
    blurb: "6.9-inch Pro display, A18 Pro performance and 256GB storage.",
    highlights: ["6.9-inch Super Retina XDR display", "A18 Pro chip", "256GB storage", "USB-C and MagSafe"],
    specs: {
      Display: "6.9-inch Super Retina XDR",
      Chip: "A18 Pro",
      Storage: "256GB",
      Finish: "Desert Titanium",
      Connectivity: "5G, Wi-Fi, Bluetooth",
      Condition: "Brand new"
    }
  },
  {
    id: 2,
    slug: "samsung-galaxy-s25-ultra-256gb",
    name: "Galaxy S25 Ultra 256GB",
    brand: "Samsung",
    category: "Phones",
    price: 1849000,
    oldPrice: 1999000,
    badge: "Featured",
    rating: 0,
    reviews: 0,
    stock: 11,
    condition: "New",
    warranty: "1 year seller warranty",
    image: "/products/samsung-galaxy-s25-ultra-256gb.webp",
    blurb: "6.9-inch Galaxy flagship with S Pen, 256GB storage and titanium frame.",
    highlights: ["6.9-inch Dynamic AMOLED 2X", "Integrated S Pen", "256GB storage", "Titanium frame"],
    specs: {
      Display: "6.9-inch Dynamic AMOLED 2X",
      Storage: "256GB",
      Color: "Titanium Gray",
      SIM: "Dual SIM",
      Connectivity: "5G, Wi-Fi, Bluetooth",
      Condition: "Brand new"
    }
  },
  {
    id: 3,
    slug: "macbook-air-m4-13-inch",
    name: "MacBook Air M4 13-inch",
    brand: "Apple",
    category: "Laptops",
    price: 2395000,
    badge: "New",
    rating: 0,
    reviews: 0,
    stock: 5,
    condition: "New",
    warranty: "1 year seller warranty",
    image: "/products/macbook-air-m4-13-inch.webp",
    blurb: "13-inch MacBook Air with M4 performance in a thin fanless design.",
    highlights: ["Apple M4 chip", "13-inch class display", "Fanless design", "USB-C and MagSafe"],
    specs: {
      Display: "13-inch class",
      Chip: "Apple M4",
      Platform: "macOS",
      Finish: "Silver",
      Condition: "Brand new"
    }
  },
  {
    id: 4,
    slug: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "Audio",
    price: 575000,
    oldPrice: 625000,
    rating: 0,
    reviews: 0,
    stock: 14,
    condition: "New",
    warranty: "6 months seller warranty",
    image: "/products/sony-wh-1000xm5.webp",
    blurb: "Wireless over-ear headphones with active noise cancellation.",
    highlights: ["Active noise cancellation", "Wireless over-ear design", "USB-C charging", "Built-in microphones"],
    specs: {
      Type: "Over-ear headphones",
      Connection: "Bluetooth",
      Charging: "USB-C",
      Color: "Black",
      Condition: "Brand new"
    }
  },
  {
    id: 5,
    slug: "anker-737-power-bank",
    name: "Anker 737 Power Bank",
    brand: "Anker",
    category: "Accessories",
    price: 185000,
    badge: "Staff pick",
    rating: 0,
    reviews: 0,
    stock: 19,
    condition: "New",
    warranty: "6 months seller warranty",
    image: "/products/anker-737-power-bank.webp",
    blurb: "24,000mAh power bank with high-output USB-C charging.",
    highlights: ["24,000mAh capacity", "Up to 140W USB-C output", "Digital power display", "2 USB-C and 1 USB-A port"],
    specs: {
      Capacity: "24,000mAh",
      Output: "Up to 140W",
      Ports: "2 USB-C, 1 USB-A",
      Display: "Digital status display",
      Condition: "Brand new"
    }
  },
  {
    id: 6,
    slug: "hollyland-lark-m2-wireless-mic",
    name: "Hollyland Lark M2 Wireless Mic",
    brand: "Hollyland",
    category: "Creator Tools",
    price: 235000,
    rating: 0,
    reviews: 0,
    stock: 9,
    condition: "New",
    warranty: "6 months seller warranty",
    image: "/products/hollyland-lark-m2-wireless-mic.webp",
    blurb: "Compact dual wireless microphone kit for phones and cameras.",
    highlights: ["Dual wireless transmitters", "Compact charging case", "Phone and camera support", "Clip-on microphone design"],
    specs: {
      Type: "Wireless microphone kit",
      Transmitters: "2",
      Use: "Phone and camera content",
      Case: "Charging case included",
      Condition: "Brand new"
    }
  },
  {
    id: 7,
    slug: "logitech-mx-master-3s",
    name: "Logitech MX Master 3S",
    brand: "Logitech",
    category: "Accessories",
    price: 185000,
    rating: 0,
    reviews: 0,
    stock: 16,
    condition: "New",
    warranty: "6 months seller warranty",
    image: "/products/logitech-mx-master-3s.webp",
    blurb: "Ergonomic wireless mouse with 8K DPI tracking and MagSpeed scrolling.",
    highlights: ["8K DPI sensor", "MagSpeed scroll wheel", "Quiet Clicks", "Multi-device workflow"],
    specs: {
      Type: "Wireless mouse",
      Sensor: "Up to 8K DPI",
      Scrolling: "MagSpeed",
      Color: "Graphite",
      Condition: "Brand new"
    }
  },
  {
    id: 8,
    slug: "jbl-charge-5",
    name: "JBL Charge 5",
    brand: "JBL",
    category: "Audio",
    price: 245000,
    oldPrice: 279000,
    badge: "Deal",
    rating: 0,
    reviews: 0,
    stock: 13,
    condition: "New",
    warranty: "6 months seller warranty",
    image: "/products/jbl-charge-5.webp",
    blurb: "Portable Bluetooth speaker with long battery life and built-in power bank.",
    highlights: ["Bluetooth audio", "Up to 20 hours of playtime", "Built-in power bank", "IP67 water and dust resistance"],
    specs: {
      Type: "Portable Bluetooth speaker",
      Battery: "Up to 20 hours",
      Protection: "IP67",
      Color: "Black",
      Condition: "Brand new"
    }
  },
  {
    id: 9,
    slug: "iphone-18-pro-256gb",
    name: "iPhone 18 Pro 256GB",
    brand: "Apple",
    category: "Phones",
    price: 1795000,
    badge: "New 2026",
    rating: 0,
    reviews: 0,
    image: "/products/iphone-18-pro-256gb.webp",
    blurb: "A20 Pro iPhone with variable-aperture 48MP Fusion main camera.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Chip: A20 Pro", "Storage: 256GB", "Camera: 48MP Fusion Main with variable aperture", "Availability: Confirm current stock before purchase"],
    specs: {"Chip":"A20 Pro","Storage":"256GB","Camera":"48MP Fusion Main with variable aperture","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 10,
    slug: "iphone-18-pro-max-256gb",
    name: "iPhone 18 Pro Max 256GB",
    brand: "Apple",
    category: "Phones",
    price: 2200000,
    badge: "New 2026",
    rating: 0,
    reviews: 0,
    image: "/products/iphone-18-pro-max-256gb.webp",
    blurb: "Large-screen A20 Pro flagship with Apple's latest Pro camera system.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Chip: A20 Pro", "Storage: 256GB", "Camera: 48MP Fusion Main with variable aperture", "Availability: Confirm current stock before purchase"],
    specs: {"Chip":"A20 Pro","Storage":"256GB","Camera":"48MP Fusion Main with variable aperture","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 11,
    slug: "airpods-5",
    name: "AirPods 5",
    brand: "Apple",
    category: "Audio",
    price: 530000,
    badge: "New 2026",
    rating: 0,
    reviews: 0,
    image: "/products/airpods-5.webp",
    blurb: "Open-ear AirPods with active noise cancellation and updated acoustics.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Open-ear wireless earbuds", "Feature: Active Noise Cancellation", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Open-ear wireless earbuds","Feature":"Active Noise Cancellation","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 12,
    slug: "apple-watch-series-12",
    name: "Apple Watch Series 12",
    brand: "Apple",
    category: "Watches",
    price: 380000,
    badge: "New 2026",
    rating: 0,
    reviews: 0,
    image: "/products/apple-watch-series-12.webp",
    blurb: "S11-powered Apple Watch with the new Health Sensing System.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Chip: S11", "Feature: Health Sensing System", "Availability: Confirm current stock before purchase"],
    specs: {"Chip":"S11","Feature":"Health Sensing System","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 13,
    slug: "apple-watch-ultra-4",
    name: "Apple Watch Ultra 4",
    brand: "Apple",
    category: "Watches",
    price: 1045000,
    badge: "New 2026",
    rating: 0,
    reviews: 0,
    image: "/products/apple-watch-ultra-4.webp",
    blurb: "Apple's latest rugged watch with S11 and extended battery life.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Chip: S11", "Battery: Up to 50 hours everyday use", "Availability: Confirm current stock before purchase"],
    specs: {"Chip":"S11","Battery":"Up to 50 hours everyday use","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 14,
    slug: "galaxy-s26-ultra-512gb",
    name: "Galaxy S26 Ultra 512GB",
    brand: "Samsung",
    category: "Phones",
    price: 1120000,
    badge: "New 2026",
    rating: 0,
    reviews: 0,
    image: "/products/galaxy-s26-ultra-512gb.webp",
    blurb: "6.9-inch Ultra flagship with 200MP camera, S Pen and Privacy Display.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Display: 6.9-inch", "Camera: 200MP wide", "Feature: Built-in Privacy Display", "Storage: 512GB"],
    specs: {"Display":"6.9-inch","Camera":"200MP wide","Feature":"Built-in Privacy Display","Storage":"512GB"}
  },
  {
    id: 15,
    slug: "galaxy-s26-plus-512gb",
    name: "Galaxy S26+ 512GB",
    brand: "Samsung",
    category: "Phones",
    price: 2065000,
    badge: "New 2026",
    rating: 0,
    reviews: 0,
    image: "/products/galaxy-s26-plus-512gb.webp",
    blurb: "Large-screen Galaxy S flagship with the 2026 Samsung platform.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Storage: 512GB", "Availability: Confirm current stock before purchase"],
    specs: {"Storage":"512GB","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 16,
    slug: "galaxy-s26-256gb",
    name: "Galaxy S26 256GB",
    brand: "Samsung",
    category: "Phones",
    price: 1390000,
    badge: "New 2026",
    rating: 0,
    reviews: 0,
    image: "/products/galaxy-s26-256gb.webp",
    blurb: "Compact 2026 Galaxy S flagship with Galaxy AI features.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Storage: 256GB", "Availability: Confirm current stock before purchase"],
    specs: {"Storage":"256GB","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 17,
    slug: "galaxy-z-fold8-ultra",
    name: "Galaxy Z Fold8 Ultra",
    brand: "Samsung",
    category: "Phones",
    price: 2335000,
    badge: "New 2026",
    rating: 0,
    reviews: 0,
    image: "/products/galaxy-z-fold8-ultra.webp",
    blurb: "Samsung's 2026 Ultra foldable built for large-screen productivity.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Foldable phone", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Foldable phone","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 18,
    slug: "galaxy-z-fold8",
    name: "Galaxy Z Fold8",
    brand: "Samsung",
    category: "Phones",
    price: 1660000,
    badge: "New 2026",
    rating: 0,
    reviews: 0,
    image: "/products/galaxy-z-fold8.webp",
    blurb: "2026 Galaxy Fold with a book-style flexible display.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Foldable phone", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Foldable phone","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 19,
    slug: "galaxy-z-flip8",
    name: "Galaxy Z Flip8",
    brand: "Samsung",
    category: "Phones",
    price: 985000,
    badge: "New 2026",
    rating: 0,
    reviews: 0,
    image: "/products/galaxy-z-flip8.webp",
    blurb: "Compact 2026 clamshell foldable from Samsung.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Flip foldable", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Flip foldable","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 20,
    slug: "galaxy-watch-ultra2",
    name: "Galaxy Watch Ultra2",
    brand: "Samsung",
    category: "Watches",
    price: 1140000,
    badge: "New 2026",
    rating: 0,
    reviews: 0,
    image: "/products/galaxy-watch-ultra2.webp",
    blurb: "Samsung's latest Ultra smartwatch for fitness and outdoor use.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Smartwatch", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Smartwatch","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 21,
    slug: "galaxy-watch9",
    name: "Galaxy Watch9",
    brand: "Samsung",
    category: "Watches",
    price: 665000,
    badge: "New 2026",
    rating: 0,
    reviews: 0,
    image: "/products/galaxy-watch9.webp",
    blurb: "2026 Galaxy smartwatch with Samsung health and wearable features.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Smartwatch", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Smartwatch","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 22,
    slug: "google-pixel-11-pro-fold",
    name: "Google Pixel 11 Pro Fold",
    brand: "Google",
    category: "Phones",
    price: 2200000,
    badge: "New 2026",
    rating: 0,
    reviews: 0,
    image: "/products/google-pixel-11-pro-fold.webp",
    blurb: "Tensor G6 foldable with 8-inch inner display and 30x Super Zoom.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Chip: Google Tensor G6", "InnerDisplay: 8-inch Super Actua Flex", "Camera: Up to 30x Super Zoom", "Availability: Confirm current stock before purchase"],
    specs: {"Chip":"Google Tensor G6","InnerDisplay":"8-inch Super Actua Flex","Camera":"Up to 30x Super Zoom","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 23,
    slug: "google-pixel-10-pro-xl",
    name: "Google Pixel 10 Pro XL",
    brand: "Google",
    category: "Phones",
    price: 1525000,
    badge: "Featured",
    rating: 0,
    reviews: 0,
    image: "/products/google-pixel-10-pro-xl.webp",
    blurb: "Large-screen Pixel flagship with Google's AI-first software experience.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Android flagship", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Android flagship","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 24,
    slug: "oneplus-15",
    name: "OnePlus 15",
    brand: "OnePlus",
    category: "Phones",
    price: 850000,
    badge: "Featured",
    rating: 0,
    reviews: 0,
    image: "/products/oneplus-15.webp",
    blurb: "Performance-focused Android flagship from OnePlus.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Android flagship", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Android flagship","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 25,
    slug: "xiaomi-15-ultra",
    name: "Xiaomi 15 Ultra",
    brand: "Xiaomi",
    category: "Phones",
    price: 1795000,
    badge: "Camera pick",
    rating: 0,
    reviews: 0,
    image: "/products/xiaomi-15-ultra.webp",
    blurb: "Camera-led Xiaomi flagship built around high-end mobile photography.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Android flagship", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Android flagship","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 26,
    slug: "iphone-17-256gb",
    name: "iPhone 17 256GB",
    brand: "Apple",
    category: "Phones",
    price: 1120000,
    badge: "Popular",
    rating: 0,
    reviews: 0,
    image: "/products/iphone-17-256gb.webp",
    blurb: "Previous-generation iPhone with strong everyday performance.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Storage: 256GB", "Availability: Confirm current stock before purchase"],
    specs: {"Storage":"256GB","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 27,
    slug: "iphone-17-pro-256gb",
    name: "iPhone 17 Pro 256GB",
    brand: "Apple",
    category: "Phones",
    price: 2065000,
    badge: "Popular",
    rating: 0,
    reviews: 0,
    image: "/products/iphone-17-pro-256gb.webp",
    blurb: "Pro iPhone for high-performance mobile photography and video.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Storage: 256GB", "Availability: Confirm current stock before purchase"],
    specs: {"Storage":"256GB","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 28,
    slug: "iphone-17-pro-max-256gb",
    name: "iPhone 17 Pro Max 256GB",
    brand: "Apple",
    category: "Phones",
    price: 1390000,
    badge: "Popular",
    rating: 0,
    reviews: 0,
    image: "/products/iphone-17-pro-max-256gb.webp",
    blurb: "Large-screen Pro iPhone with premium camera and battery focus.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Storage: 256GB", "Availability: Confirm current stock before purchase"],
    specs: {"Storage":"256GB","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 29,
    slug: "ipad-air-m3-11",
    name: "iPad Air M3 11-inch",
    brand: "Apple",
    category: "Tablets",
    price: 2475000,
    badge: "Featured",
    rating: 0,
    reviews: 0,
    image: "/products/ipad-air-m3-11.webp",
    blurb: "M3-powered iPad Air for study, work and creative apps.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Chip: Apple M3", "Display: 11-inch class", "Availability: Confirm current stock before purchase"],
    specs: {"Chip":"Apple M3","Display":"11-inch class","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 30,
    slug: "ipad-pro-m5-13",
    name: "iPad Pro M5 13-inch",
    brand: "Apple",
    category: "Tablets",
    price: 1750000,
    badge: "Pro",
    rating: 0,
    reviews: 0,
    image: "/products/ipad-pro-m5-13.webp",
    blurb: "High-end iPad Pro for creative and professional tablet workflows.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Chip: Apple M5", "Display: 13-inch class", "Availability: Confirm current stock before purchase"],
    specs: {"Chip":"Apple M5","Display":"13-inch class","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 31,
    slug: "galaxy-tab-s11-ultra",
    name: "Galaxy Tab S11 Ultra",
    brand: "Samsung",
    category: "Tablets",
    price: 1025000,
    badge: "Featured",
    rating: 0,
    reviews: 0,
    image: "/products/galaxy-tab-s11-ultra.webp",
    blurb: "Large Samsung tablet for productivity, drawing and media.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Android tablet", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Android tablet","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 32,
    slug: "macbook-pro-14-m5",
    name: "MacBook Pro 14-inch M5",
    brand: "Apple",
    category: "Laptops",
    price: 2850000,
    badge: "Pro",
    rating: 0,
    reviews: 0,
    image: "/products/macbook-pro-14-m5.webp",
    blurb: "14-inch MacBook Pro for development, design and creative production.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Chip: Apple M5", "Display: 14-inch class", "Availability: Confirm current stock before purchase"],
    specs: {"Chip":"Apple M5","Display":"14-inch class","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 33,
    slug: "rog-zephyrus-g14-2026",
    name: "ROG Zephyrus G14 2026",
    brand: "ASUS",
    category: "Laptops",
    price: 1975000,
    badge: "New 2026",
    rating: 0,
    reviews: 0,
    image: "/products/rog-zephyrus-g14-2026.webp",
    blurb: "14-inch 3K OLED gaming laptop with 2026 Ryzen AI or Core Ultra configurations.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Display: 14-inch 3K OLED 120Hz", "Graphics: RTX 50-series configurations", "Availability: Confirm current stock before purchase"],
    specs: {"Display":"14-inch 3K OLED 120Hz","Graphics":"RTX 50-series configurations","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 34,
    slug: "dell-xps-14",
    name: "Dell XPS 14",
    brand: "Dell",
    category: "Laptops",
    price: 3200000,
    badge: "Premium",
    rating: 0,
    reviews: 0,
    image: "/products/dell-xps-14.webp",
    blurb: "Compact premium Windows laptop for professional work.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Windows laptop", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Windows laptop","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 35,
    slug: "thinkpad-x1-carbon",
    name: "ThinkPad X1 Carbon",
    brand: "Lenovo",
    category: "Laptops",
    price: 2325000,
    badge: "Business",
    rating: 0,
    reviews: 0,
    image: "/products/thinkpad-x1-carbon.webp",
    blurb: "Lightweight business laptop with ThinkPad keyboard and security focus.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Business laptop", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Business laptop","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 36,
    slug: "hp-spectre-x360-14",
    name: "HP Spectre x360 14",
    brand: "HP",
    category: "Laptops",
    price: 1450000,
    badge: "2-in-1",
    rating: 0,
    reviews: 0,
    image: "/products/hp-spectre-x360-14.webp",
    blurb: "Premium convertible Windows laptop for mobile work.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: 2-in-1 laptop", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"2-in-1 laptop","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 37,
    slug: "airpods-pro-3",
    name: "AirPods Pro 3",
    brand: "Apple",
    category: "Audio",
    price: 670000,
    badge: "Popular",
    rating: 0,
    reviews: 0,
    image: "/products/airpods-pro-3.webp",
    blurb: "In-ear AirPods Pro with noise cancellation and Apple ecosystem features.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: True wireless earbuds", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"True wireless earbuds","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 38,
    slug: "airpods-max-2",
    name: "AirPods Max 2",
    brand: "Apple",
    category: "Audio",
    price: 320000,
    badge: "Premium",
    rating: 0,
    reviews: 0,
    image: "/products/airpods-max-2.webp",
    blurb: "Apple over-ear headphones with premium materials and noise control.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Over-ear headphones", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Over-ear headphones","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 39,
    slug: "sony-wh-1000xm6",
    name: "Sony WH-1000XM6",
    brand: "Sony",
    category: "Audio",
    price: 810000,
    badge: "Noise cancelling",
    rating: 0,
    reviews: 0,
    image: "/products/sony-wh-1000xm6.webp",
    blurb: "Sony premium wireless headphones for travel and focused listening.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Over-ear headphones", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Over-ear headphones","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 40,
    slug: "bose-quietcomfort-ultra",
    name: "Bose QuietComfort Ultra",
    brand: "Bose",
    category: "Audio",
    price: 460000,
    badge: "Premium",
    rating: 0,
    reviews: 0,
    image: "/products/bose-quietcomfort-ultra.webp",
    blurb: "High-end Bose wireless headphones with immersive audio and ANC.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Over-ear headphones", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Over-ear headphones","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 41,
    slug: "marshall-emberton-iii",
    name: "Marshall Emberton III",
    brand: "Marshall",
    category: "Audio",
    price: 950000,
    badge: "Portable",
    rating: 0,
    reviews: 0,
    image: "/products/marshall-emberton-iii.webp",
    blurb: "Compact portable speaker with Marshall styling and travel-friendly design.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Bluetooth speaker", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Bluetooth speaker","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 42,
    slug: "dji-mic-3",
    name: "DJI Mic 3",
    brand: "DJI",
    category: "Creator Tools",
    price: 730000,
    badge: "Creator",
    rating: 0,
    reviews: 0,
    image: "/products/dji-mic-3.webp",
    blurb: "Compact wireless microphone system for mobile and camera production.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Wireless microphone system", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Wireless microphone system","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 43,
    slug: "rode-wireless-pro",
    name: "RØDE Wireless PRO",
    brand: "RØDE",
    category: "Creator Tools",
    price: 305000,
    badge: "Creator",
    rating: 0,
    reviews: 0,
    image: "/products/rode-wireless-pro.webp",
    blurb: "Professional dual-channel wireless audio kit for creators and interviews.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Wireless microphone system", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Wireless microphone system","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 44,
    slug: "insta360-x5",
    name: "Insta360 X5",
    brand: "Insta360",
    category: "Creator Tools",
    price: 900000,
    badge: "Creator",
    rating: 0,
    reviews: 0,
    image: "/products/insta360-x5.webp",
    blurb: "360 camera for action, travel and reframed social video.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: 360 camera", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"360 camera","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 45,
    slug: "dji-osmo-pocket-3",
    name: "DJI Osmo Pocket 3",
    brand: "DJI",
    category: "Creator Tools",
    price: 475000,
    badge: "Creator",
    rating: 0,
    reviews: 0,
    image: "/products/dji-osmo-pocket-3.webp",
    blurb: "Pocket gimbal camera for stabilized handheld video.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Gimbal camera", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Gimbal camera","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 46,
    slug: "logitech-brio-4k",
    name: "Logitech Brio 4K",
    brand: "Logitech",
    category: "Creator Tools",
    price: 1070000,
    badge: "Streaming",
    rating: 0,
    reviews: 0,
    image: "/products/logitech-brio-4k.webp",
    blurb: "4K webcam for meetings, streaming and desktop content production.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Webcam", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Webcam","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 47,
    slug: "elgato-key-light",
    name: "Elgato Key Light",
    brand: "Elgato",
    category: "Creator Tools",
    price: 645000,
    badge: "Streaming",
    rating: 0,
    reviews: 0,
    image: "/products/elgato-key-light.webp",
    blurb: "Desk-mounted LED key light for streaming and video calls.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: LED key light", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"LED key light","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 48,
    slug: "samsung-t9-ssd-2tb",
    name: "Samsung T9 Portable SSD 2TB",
    brand: "Samsung",
    category: "Accessories",
    price: 95000,
    badge: "Storage",
    rating: 0,
    reviews: 0,
    image: "/products/samsung-t9-ssd-2tb.webp",
    blurb: "Fast portable SSD for project files, backups and creator workflows.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Capacity: 2TB", "Type: Portable SSD", "Availability: Confirm current stock before purchase"],
    specs: {"Capacity":"2TB","Type":"Portable SSD","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 49,
    slug: "ugreen-nexode-200w",
    name: "UGREEN Nexode 200W Charger",
    brand: "UGREEN",
    category: "Accessories",
    price: 340000,
    badge: "Power",
    rating: 0,
    reviews: 0,
    image: "/products/ugreen-nexode-200w.webp",
    blurb: "High-output multi-port desktop charger for laptops, phones and accessories.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Output: Up to 200W", "Type: USB-C charger", "Availability: Confirm current stock before purchase"],
    specs: {"Output":"Up to 200W","Type":"USB-C charger","Availability":"Confirm current stock before purchase"}
  },
  {
    id: 50,
    slug: "nintendo-switch-2",
    name: "Nintendo Switch 2",
    brand: "Nintendo",
    category: "Gaming",
    price: 800000,
    badge: "Gaming",
    rating: 0,
    reviews: 0,
    image: "/products/nintendo-switch-2.webp",
    blurb: "Nintendo's current hybrid console for handheld and TV play.",
    stock: 0,
    warranty: "Confirm before purchase",
    condition: "New",
    highlights: ["Type: Hybrid game console", "Availability: Confirm current stock before purchase"],
    specs: {"Type":"Hybrid game console","Availability":"Confirm current stock before purchase"}
  }
];

export const money = (value: number) => value > 0 ? `₦${value.toLocaleString("en-NG")}` : "Price on request";
export const getProduct = (slug: string) => products.find((product) => product.slug === slug);
